### ISSUE TITLE
Vitest tests are failing on out of the box project config

### ISSUE THREAD

**Issue by johnatawnclementawn** [archesproject/arches-references#2]
See [failing tests](https://github.com/archesproject/arches-references/actions/runs/10150010033/job/28066157363?pr=1), which we were able to resolve in [this commit](https://github.com/archesproject/arches-references/pull/1/commits/cb8725f8b0b6d94104593beaa729cf209061f49b) by commenting out `import '@/declarations.d.ts';`.

I was unable to reproduce this in a blank v7.6 project, and copying over the `arches-references` front-end src files, which leads me to believe that I messed something up during the initialization of this arches app. I confirmed that `declarations.d.ts`, `declarations.test.ts`, `vitest.setup.mts`, `vitest.config.mts`, and `tsconfig.json` are the same between `arches-references` and this new project (except for namespace in `tsconfig.json`).

**Comment by jacobtylerwalls** [comment]
No longer an issue
